name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: 'frontend-ui'
          node-version: 12.x
          cache: yarn
      - name: Install Dependencies
        working-directory: 'frontend-ui'
        run: yarn
      - name: Lint
        working-directory: 'frontend-ui'
        run: yarn run lint

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: 'frontend-ui'
          node-version: 12.x
          cache: yarn
      - name: Install Dependencies
        working-directory: 'frontend-ui'
        run: yarn
      - name: Run Tests
        working-directory: 'frontend-ui'
        run: yarn test